### ISSUE TITLE
add assignments route

### ISSUE THREAD

**Issue by le-jeu** [wasabee-project/Wasabee-Server#11]
At the moment, there is no route for an agent to see the assignment that is not restricted by read permission. (except for `pDrawMyRouteRoute`)

https://github.com/wasabee-project/Wasabee-Server/blob/bd09091f11580046b4d6e774b04096b3ec71f6cc/http/draw.go#L80

An agent can see that (s)he has assignment on some OP, but he can't see the assignments.

The agent should have a way to consult all assignments from any OP using ↓
https://github.com/wasabee-project/Wasabee-Server/blob/bd09091f11580046b4d6e774b04096b3ec71f6cc/model_draw_assignments.go#L15

The side effect of the first point is : 
 - an assign-only OP is listed in one's profile, so wasabee-iitc try to get OP details on sync, fails and none OP is synced
https://github.com/wasabee-project/Wasabee-IITC/blob/bbdd4f47a456ffe7fb6b11c2590874ca03006d35/src/code/buttons/syncButton.js#L49
https://github.com/wasabee-project/Wasabee-IITC/blob/bbdd4f47a456ffe7fb6b11c2590874ca03006d35/src/code/server.js#L217
 - wasabee-mobile hang on permission denied (ok, its unsupported for now)

**Comment by cloudkucooland** [comment]
OK, will fix soon.

**Comment by cloudkucooland** [comment]
The access control line should have been:

	if !o.ReadAccess(gid) && !o.AssignedOnlyAccess(gid) {

The populate call determines if it should be the full op or just the assignments (permissions are checked again).

With this change, assigned only permissions should "just work" for all ops.

https://github.com/wasabee-project/Wasabee-Server/commit/224ba2f9951050d19f6a758fced53ef1cd44a041#diff-43b611c25c91b173eec1d74b6892b722

**Comment by cloudkucooland** [comment]
fixed, seems confirmed by users.
