### ISSUE TITLE
Task Completion Setup....

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-Server#8]
When an Op is in progress / Complete, there needs to be a way to quickly state "task Complete" to the operator with other quick options...

Telegram Response PRIMARY

/assignments
(Lists assignments)
would be like:
George Orwell Lucky Candlestick (Complete) (Next)( Pending)

Wasabee App Secondarly
Menu, then Assignments with a checkbox for each of the above.

In IITC
In Operation Checklist:  Anyone with Edit permissions can Double click the "Pending" to change the state to Complete.  Double click a Second time would take it back to Pending.

**Comment by cloudkucooland** [comment]
The IITC stuff is in place. When an agent marks a task as complete, it triggers a firebase alert which lets everyone on the team know that it was done instantly.

**Comment by cloudkucooland** [comment]
I think this one is covered now
