### ISSUE TITLE
Time between agent and target

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-Server#9]
"Show time between agent and target"
https://github.com/googlemaps/google-maps-services-go
https://developers.google.com/maps/documentation/javascript/distancematrix

**Comment by cloudkucooland** [comment]
does this better belong in the clients?

**Comment by TheMitch2** [comment]
The app for sure. I think there's debate for the plugin drive you can basically do this through IITC portal details>share portal

**Comment by cloudkucooland** [comment]
belongs in the client
